# Generated by Django 6.1 on 2026-09-20 09:38

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_project_alter_experience_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='tech_stack',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='project',
            name='type',
            field=models.CharField(choices=[('personal', 'Personal'), ('group', 'Group')], default='Personal', max_length=20),
        ),
        migrations.AlterField(
            model_name='project',
            name='started_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
