# Generated by Django 6.1 on 2026-09-20 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_project_tech_stack_project_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='type',
            field=models.CharField(choices=[('personal', 'Personal'), ('group', 'Group')], max_length=20),
        ),
    ]
