# Generated by Django 6.1 on 2026-09-22 15:27

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_experience_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Achievment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('descriptions', models.TextField()),
                ('level', models.CharField(choices=[('campus', 'Campus'), ('national', 'National'), ('international', 'International')], default='Campus')),
                ('achieved_at', models.DateField(default=django.utils.timezone.now)),
            ],
        ),
    ]
