# Generated by Django 6.1 on 2026-09-22 15:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_achievment'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Achievment',
            new_name='Achievement',
        ),
    ]
