# Generated by Django 6.1 on 2026-09-22 16:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_rename_achievment_achievement'),
    ]

    operations = [
        migrations.RenameField(
            model_name='achievement',
            old_name='descriptions',
            new_name='description',
        ),
    ]
