# Generated by Django 6.1 on 2026-09-22 17:04

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_rename_descriptions_achievement_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='achievement',
            name='achieved_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
