# Generated by Django 6.1 on 2026-09-22 17:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_alter_achievement_achieved_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='achievement',
            name='achieved_at',
            field=models.DateTimeField(default=datetime.datetime(2026, 9, 22, 17, 5, 56, 585930, tzinfo=datetime.timezone.utc)),
        ),
    ]
