# Generated by Django 6.1 on 2026-09-22 17:06

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_alter_achievement_achieved_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='achievement',
            name='achieved_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
