# Generated by Django 6.1 on 2026-09-22 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_alter_achievement_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='achievement',
            name='level',
            field=models.CharField(choices=[('campus', 'Campus'), ('national', 'National'), ('international', 'International')], default='campus'),
        ),
    ]
