# Generated by Django 6.1 on 2026-09-22 23:08

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0015_alter_achievement_level"),
    ]

    operations = [
        migrations.AlterField(
            model_name="achievement",
            name="achieved_at",
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
