# Generated by Django 6.1 on 2026-09-27 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0016_alter_achievement_achieved_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="experience",
            name="category",
            field=models.CharField(
                choices=[
                    ("internship", "Internship"),
                    ("research", "Research"),
                    ("volunteer", "Volunteer"),
                    ("part-time", "Part-Time"),
                    ("full-time", "Full-Time"),
                    ("freelance", "Freelance"),
                    ("competition", "Competition"),
                ],
                max_length=20,
            ),
        ),
    ]
